//module1.js 
let CityHomePage =
{
	name1: "Alhambra - L.A./CA",
	name2: "Azusa - L.A./CA",
	name3: "Baldwin Park - L.A./CA",
	name4: "Covina - L.A./CA",
	name5: "Diamond Bar - L.A./CA",
	name6: "El Monte - L.A./CA",
	name7: "Industry - L.A./CA",
	name8: "Irwindale - L.A./CA",
	name9: "La Puente - L.A./CA",
	name10: "Los Angeles - L.A./CA",
	name11: "Montebello - L.A./CA",
	name12: "Monterey Park - L.A./CA",
	name13: "Pomona - L.A./CA",
	name14: "Rosemead - L.A./CA",
	name15: "San Gabriel - L.A./CA",
	name16: "South El Monte - L.A./CA",
	name17: "Walnut - L.A./CA",
	name18: "West Covina - L.A./CA",
	name19: "Agoura Hills - L.A./CA",
	name20: "Beverly Hills - L.A./CA",
	name21: "Calabasas - L.A./CA",
	name22: "Carson - L.A./CA",
	name23: "Compton - L.A./CA",
	name24: "Culver City - L.A./CA",
	name25: "El Segundo - L.A./CA",
	name26: "Gardena - L.A./CA",
	name27: "Hawthorne - L.A./CA",
	name28: "Hermosa Beach - L.A./CA",
	name29: "Hidden Hills - L.A./CA",
	name30: "Inglewood - L.A./CA",
	name31: "Lawndale - L.A./CA",
	name32: "Malibu - L.A./CA",
	name33: "Manhattan Beach - L.A./CA",
	name34: "Redondo Beach - L.A./CA",
	name35: "San Fernando - L.A./CA",
	name36: "Santa Monica - L.A./CA",
	name37: "West Hollywood - L.A./CA",
	name38: "Westlake Village - L.A./CA",
	name39: "Avalon - L.A./CA",
	name40: "Bell - L.A./CA",
	name41: "Bell Gardens - L.A./CA",
	name42: "Bellflower - L.A./CA",
	name43: "Commerce - L.A./CA",
	name44: "Cudahy - L.A./CA",
	name45: "Downey - L.A./CA",
	name46: "Huntington Park - L.A./CA",
	name47: "La Habra Heights - L.A./CA",
	name48: "La Mirada - L.A./CA",
	name49: "Lakewood - L.A./CA",
	name50: "Lomita - L.A./CA",
	name51: "Long Beach - L.A./CA",
	name52: "Lynwood - L.A./CA",
	name53: "Maywood - L.A./CA",
	name54: "Norwalk - L.A./CA",
	name55: "Palos Verdes Estate - L.A./CA",
	name56: "Paramount - L.A./CA",
	name57: "Pico Rivera - L.A./CA",
	name58: "Rancho Palos Verdes - L.A./CA",
	name59: "Rolling Hills - L.A./CA",
	name60: "San Catalina Island - L.A./CA",
	name61: "San Clemente Island - L.A./CA",
	name62: "Santa Fe Springs - L.A./CA",
	name63: "Signal Hills - L.A./CA",
	name64: "South Gate - L.A./CA",
	name65: "Torrance - L.A./CA",
	name66: "Vernon - L.A./CA",
	name67: "Whittier - L.A./CA",
	name68: "Arcadia - L.A./CA",
	name69: "Bradbury - L.A./CA",
	name70: "Burbank - L.A./CA",
	name71: "Claremont - L.A./CA",
	name72: "Duarte - L.A./CA",
	name73: "Glendale - L.A./CA",
	name74: "Glendora - L.A./CA",
	name75: "La Canada Flintridge - L.A./CA",
	name76: "La Verne - L.A./CA",
	name77: "Lancaster - L.A./CA",
	name78: "Monrovia - L.A./CA",
	name79: "Palmdale - L.A./CA",
	name80: "Pasadena - L.A./CA",
	name81: "San Dimas - L.A./CA",
	name82: "San Marino - L.A./CA",
	name83: "Santa Clarita - L.A./CA",
	name84: "Sierra Madre - L.A./CA",
	name85: "South Pasadena - L.A./CA",
	name86: "Temple City - L.A./CA",
	name87: "Boulder City - Clark/NV",
	name88: "Bunkerville - Clark/NV",
	name89: "Cal_Nev_Ari - Clark/NV",
	name90: "Corn Creek - Clark/NV",
	name91: "Coyotte Springs - Clark/NV",
	name92: "Echo Bay - Clark/NV",
	name93: "Henderson - Clark/NV",
	name94: "Indian Springs - Clark/NV",
	name95: "Jean - Clark/NV",
	name96: "Las Vegas - Clark/NV",
	name97: "Laughlin - Clark/NV",
	name98: "Moapa Valley - Clark/NV",
	name99: "Mosquite - Clark/NV",
	name100: "Overturn - Clark/NV",
	name101: "Primm - Clark/NV",
	name102: "Sandy Valley - Clark/NV",
	name103: "Searchlight - Clark/NV",
	name104: "Sloan - Clark/NV",
	name105: "Southern Desert Correctional Center - Clark/NV",
	/*
	name106: "Rutherfordium - Clark/NV",
	name107: "Dubnium - Clark/NV",
	name108: "Seaborgium - Clark/NV",
	name109: "Bohrium - Clark/NV",
	name110: "Hassium - Clark/NV",
	name111: "Meitnerium - Clark/NV",
	name112: "Darmstadtium - Clark/NV",
	name113: "Roentgenium",
	name114: "Copernicium",
	name115: "Ununtrium",
	name116: "Flerovium",
	name117: "Ununpentium",
	name118: "Livermorium",
	name119: "Ununseptium",
	name120: "Ununoctium",
	*/
};